### ISSUE TITLE
Not correctly state the humidity sensor is connected BME280

### ISSUE THREAD

**Issue by NikolayUlianov** [ausHaus/ioBroker.megadd#5]
Not correctly state the humidity sensor is connected BME280
![2018-09-27_09-38-17](https://user-images.githubusercontent.com/43374650/46141639-39119200-c25d-11e8-8025-365dff07a268.png)
![2018-09-27_09-38-36](https://user-images.githubusercontent.com/43374650/46141640-39119200-c25d-11e8-95bd-022e4576a164.png)
![2018-09-27_13-18-28](https://user-images.githubusercontent.com/43374650/46141641-39119200-c25d-11e8-8dc2-f9d6385cbfa4.png)

**Comment by NikolayUlianov** [comment]
![image](https://user-images.githubusercontent.com/43374650/46142191-d28d7380-c25e-11e8-8aeb-59752785657b.png)

**Comment by NikolayUlianov** [comment]
![image](https://user-images.githubusercontent.com/43374650/46142212-e89b3400-c25e-11e8-8bf2-d4606e47f9b3.png)

**Comment by ausHaus** [comment]
Do not rename the ports were with this problem

**Comment by NikolayUlianov** [comment]
The ports with the original names have been re-preserved. Nothing has changed.
![image](https://user-images.githubusercontent.com/43374650/46290777-70ea4380-c595-11e8-948a-a6749a5df0be.png)
![image](https://user-images.githubusercontent.com/43374650/46290816-89f2f480-c595-11e8-9e5a-69dc4e330174.png)

**Comment by NikolayUlianov** [comment]
![image](https://user-images.githubusercontent.com/43374650/46290902-c45c9180-c595-11e8-8d84-f0372a96f93e.png)

**Comment by ausHaus** [comment]
let's continue on the forum ioBroker https://forum.iobroker.net/viewtopic.php?f=16&t=4076
